site_name: FastOpenAPI
site_url: https://fastopenapi.fatalyst.dev/
site_description: FastOpenAPI is a library for generating and integrating OpenAPI schemas using Pydantic and various frameworks.
repo_name: mr-fatalyst/fastopenapi
repo_url: https://github.com/mr-fatalyst/fastopenapi

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green
      accent: light green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
  - content.code.annotate
  - content.code.copy
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  icon:
    repo: fontawesome/brands/github
  logo: img/favicon.png
  favicon: img/favicon.png
  language: en

nav:
  - FastOpenAPI: index.md
  - Erste Schritte:
      - Installation: getting_started/installation.md
      - Schnellstart: getting_started/quickstart.md
      - Verwendung: getting_started/usage.md
  - Frameworks:
      - AIOHTTP: frameworks/aiohttp.md
      - Falcon: frameworks/falcon.md
      - Flask: frameworks/flask.md
      - Quart: frameworks/quart.md
      - Sanic: frameworks/sanic.md
      - Starlette: frameworks/starlette.md
      - Tornado: frameworks/tornado.md
  - Erweitert:
      - Erweiterte Verwendung: advanced/advanced_usage.md
      - API-Referenz: advanced/api_reference.md
  - Mitwirken: contributing.md
  - Änderungsprotokoll: changelog.md
  - FAQ: faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mr-fatalyst/fastopenapi
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/nikita-ryzhenkov
    - icon: fontawesome/solid/envelope
      link: mailto:nikita.ryzhenkoff@gmail.com
  alternate:
    - link: /de/
      name: de - Deutsch
    - link: /
      name: en - English
    - link: /es/
      name: es - Español
    - link: /fr/
      name: fr - Français
    - link: /ru/
      name: ru - Русский
