name: Deploy docs

on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install MkDocs
      run: pip install mkdocs-material

    - name: Build Documentation
      run: |
        mkdocs build -f docs/en/mkdocs.yml -d $(pwd)/site
        mkdocs build -f docs/ru/mkdocs.yml -d $(pwd)/site/ru
        mkdocs build -f docs/es/mkdocs.yml -d $(pwd)/site/es
        mkdocs build -f docs/de/mkdocs.yml -d $(pwd)/site/de
        mkdocs build -f docs/fr/mkdocs.yml -d $(pwd)/site/fr

    - name: Ensure site exists
      run: mkdir -p site

    - name: Write CNAME
      run: echo 'fastopenapi.fatalyst.dev' > site/CNAME

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
