name: Test CI

on:
  pull_request:
    branches:
      - test

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment (lint)
        uses: ./.github/actions/setup-env
        with:
          python-version: "3.10"
          install-flags: "--all-extras"

      - name: Run linters
        run: poetry run pre-commit run --all-files

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment (test)
        uses: ./.github/actions/setup-env
        with:
          python-version: "3.10"
          install-flags: "--all-extras"

      - name: Run tests
        run: poetry run pytest
